version: '2'

services:
  app:
    image: fabs/react-loja
    ports:
      - "80:80"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/reactloja
      - ROOT_URL=http://pontos.reativo.com

  mongo:
    image: mongo:latest
