version: '2'

services:
  app:
    build: ./board
    ports:
      - "80:80"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/reactloja
      - ROOT_URL=http://localhost
    command: meteor -p 80
    volumes:
      - "./board:/app"

  mongo:
    image: mongo:latest
